:numbered:
[[ch1_summary_of_toppers_kernel]]
== TOPPERS新世代カーネルの概要

TOPPERS新世代カーネルとは，TOPPERSプロジェクトにおいてITRON仕様をベース
として開発している一連のリアルタイムカーネルの総称である．この章では，
TOPPERS新世代カーネル仕様の位置付けと設計方針，それに属する各カーネルの
適用対象領域と設計方針について述べる．

=== TOPPERS新世代カーネル仕様の位置付け
TOPPERSプロジェクトでは，2000年に公開したTOPPERS/JSPカーネルを始めとし
て，μITRON4.0仕様およびその保護機能拡張（μITRON4.0/PX仕様）に準拠した
リアルタイムカーネルを開発してきた．

μITRON4.0仕様は1999年に，μITRON4.0/PX仕様は2002年に公表されたが，それ
以降現在までの間に，大きな仕様改訂は実施されていない．その間に，組込み
システムおよびソフトウェアのますますの大規模化・複雑化，これまで以上に
高い信頼性・安全性に対する要求，小さい消費エネルギー下での高い性能要求
など，組込みシステム開発を取り巻く状況は刻々変化している．リアルタイム
カーネルに対しても，マルチプロセッサへの対応，発展的な保護機能のサポー
ト，機能安全対応，省エネルギー制御機能のサポートなど，新しい要求が生じ
ている．

TOPPERSプロジェクトでは，リアルタイムカーネルに対するこのような新しい要
求に対応するために，μITRON4.0仕様を発展させる形で，TOPPERS新世代カーネ
ル仕様を策定することになった．

ただし，ITRON仕様が，各社が開発するリアルタイムカーネルを標準化すること
を目的に，リアルタイムカーネルの「標準仕様」を規定することを目指してい
るのに対して，TOPPERS新世代カーネル仕様は，TOPPERSプロジェクトにおいて
開発している一連のリアルタイムカーネルの「実装仕様」を記述するものであ
り，ITRON仕様とは異なる目的・位置付けを持つものである．

=== TOPPERS新世代カーネル仕様の設計方針

TOPPERS新世代カーネル仕様を設計するにあたり，次の方針を設定する．

. μITRON4.0仕様をベースに拡張・改良を加える +
+
TOPPERS新世代カーネル仕様は，多くの技術者の尽力により作成され，多くの実
装・使用実績があるμITRON4.0仕様をベースとする．ただし，μITRON4.0仕様
の策定時以降の状況の変化を考慮し，μITRON4.0仕様で不十分と考えられる点
については積極的に拡張・改良する．μITRON4.0仕様への準拠性にはこだわら
ない．

. ソフトウェアの再利用性を重視する +
+
μITRON4.0仕様の策定時点と比べると，組込みソフトウェアの大規模化が進展
している一方で，ハードウェアの性能向上も著しい．そのため，ソフトウェア
の再利用性を向上させるためには，少々のオーバヘッドは許容される状況にあ
る．
+
そこで，TOPPERS新世代カーネル仕様では，μITRON4.0仕様においてオーバヘッ
ド削減のために実装定義または実装依存としていたような項目についても，ター
ゲットシステムに依存する項目とするのではなく，強く規定する方針とする．

. 高信頼・安全なシステム構築を支援する +
+
TOPPERS新世代カーネル仕様は，高信頼・安全な組込みシステム構築を支援する
ものとする．
+
安全性の面では，アプリケーションプログラムに問題がある場合でも，リーゾ
ナブルなオーバヘッドでそれを救済できるなら，救済するような仕様とする．
また，アプリケーションプログラムの誤動作を検出する機能や，システムの自
己診断のための機能についても，順次取り込んでいく．

. アプリケーションシステム構築に必要な機能は積極的に取り込む +
+
上記の方針を満たした上で，多くのアプリケーションシステムに共通に必要と
なる機能については，積極的にカーネルに取り込む．
+
カーネル単体の信頼性を向上させるためには，カーネルの機能は少なくした方
が楽である．しかし，アプリケーションシステム構築に必要となる機能は，カー
ネルがサポートしていなければアプリケーションプログラムで実現しなければ
ならず，システム全体の信頼性を考えると，多くのアプリケーションシステム
に共通に必要となる機能については，カーネルに取り込んだ方が有利である．

=== TOPPERS/ASPカーネルの適用対象領域と仕様設計方針

TOPPERS/ASPカーネル（ASPは，Advanced Standard Profileの略．以下，ASPカー
ネル）は，TOPPERS新世代カーネルの出発点となるリアルタイムカーネルである．
保護機能を持ったカーネルやマルチプロセッサ対応のカーネルは，ASPカーネル
を拡張する形で開発する．

ASPカーネルは，20年以上に渡るITRON仕様の技術開発成果をベースとして，完
成度の高いリアルタイムカーネルを実現するものである．完成度を高めるとい
う観点から，カーネル本体の仕様については，枯れた技術で実装できる範囲に
留める．

ASPカーネルの主な適用対象は，高い信頼性・安全性・リアルタイム性を要求さ
れる組込みシステムとする．ソフトウェア規模の面では，プログラムサイズ
（バイナリコード）が数十KB〜1MB程度のシステムを主な適用対象とする．それ
より大規模なシステムには，保護機能を持ったリアルタイムカーネルを適用す
べきと考えられる．

ASPカーネルの機能は，カーネル内で動的なメモリ管理が不要な範囲に留める．
これは，高い信頼性・安全性・リアルタイム性を要求される組込みシステムで
は，システム稼働中に発生するメモリ不足への対処が難しいためである．この
方針から，カーネルオブジェクトは静的に生成することとし，動的なオブジェ
クト生成機能は設けない．ただし，アプリケーションプログラムが動的なメモ
リ管理をするためのカーネル機能である固定長メモリプール機能はサポートす
る．

=== TOPPERS/FMPカーネルの適用対象領域と仕様設計方針

TOPPERS/FMPカーネル（FMPは，Flexible Multiprocessor Profileの略．以下，
FMPカーネル）は，ASPカーネルを，マルチプロセッサ対応に拡張したリアルタ
イムカーネルである．

FMPカーネルの適用対象となるターゲットハードウェアは，ホモジニアスなマル
チプロセッサシステムである．各プロセッサが全く同一のものである必要はな
いが，すべてのプロセッサでバイナリコードを共有することから，同じバイナ
リコードを実行できることが必要である．

FMPカーネルでは，タスクを実行するプロセッサを静的に決定するのが基本であ
り，カーネルは自動的に負荷分散する機能を持たないが，タスクをマイグレー
ションさせるサービスコールを備えている．これを用いて，アプリケーション
で動的な負荷分散を実現することが可能である．

FMPカーネルの機能は，ASPカーネルと同様に，カーネル内で動的なメモリ管理
が不要な範囲に留める．

=== TOPPERS/HRP2カーネルの適用対象領域と仕様設計方針

TOPPERS/HRP2カーネル（HRPは，High Reliable system Profileの略．2はバー
ジョン番号を示す．以下，HRP2カーネル）は，さらに高い信頼性・安全性を要
求される組込みシステムや，より大規模な組込みシステム向けに適用できるよ
うに，ASPカーネルを拡張したリアルタイムカーネルである．

HRP2カーネルの適用対象となるターゲットハードウェアは，特権モードと非特
権モードを備え，メモリ保護のためにMMU（Memory Management Unit）または
MPU（Memory Protection Unit）を持つプロセッサを用いたシステムである．
HRP2カーネルの主な適用対象は，ソフトウェア規模の面では，プログラムサイ
ズ（バイナリコード）が数百KB以上のシステムである．

HRP2カーネルの機能は，ASPカーネルと同様に，カーネル内で動的なメモリ管理
が不要な範囲に留める．具体的には，ASPカーネルに対して，メモリ保護機能と
オブジェクトアクセス保護機能，拡張サービスコール機能，ミューテックス機
能，オーバランハンドラ機能を追加し，メールボックス機能を削除している．

=== TOPPERS/SSPカーネルの適用対象領域と仕様設計方針

TOPPERS/SSPカーネル（SSPは，Smallest Set Profileの略．以下，SSPカーネル）
は，小規模システムに用いるために，ASPカーネルをベースに可能な限り機能を
絞り込んだリアルタイムカーネルである．

SSPカーネルの機能は，μITRON4.0仕様の「仕様準拠の最低条件」の考え方を踏
襲し，メモリ使用量を最小化するように定めている．具体的には，SSPカーネル
においては，タスクは待ち状態を持たない（言い換えると，制約タスクのみを
サポートする）のが最大の特徴である．また，ASPカーネルに対して下位互換性
を持つように配慮しているが，システム全体のメモリ使用量を最小化するため
に有用な機能は，ASPカーネルに対して追加している．

TOPPERS/SSPカーネルの主な適用対象は，プログラムサイズ（バイナリコード）
が数KB〜数十KB程度の極めて小規模な組込みシステムである．

=== TOPPERS/ASP Safetyカーネルの適用対象領域と仕様設計方針

TOPPERS/ASP Safetyカーネル（以下，ASP Safetyカーネル）は，小規模な安全
関連システムに用いるために，ASPカーネルの機能を徹底的な検証が可能な範囲
にサブセット化したものである．メールボックスのように安全性の観点から問
題のある機能や，タスク例外処理機能のように使用頻度に比べて検証にコスト
のかかる機能はサポートしない．

ASP Safetyカーネルの主な適用対象は，特に高い安全性を要求される組込みシ
ステムとする．ソフトウェア規模の面では，プログラムサイズ（バイナリコー
ド）が数十KB〜1MB程度のシステムを主な適用対象とする．それより大規模なシ
ステムには，保護機能を持ったカーネルを適用すべきと考えられる．

