= TOPPERS新世代カーネル統合仕様書
:toc-title: 目次
:toc:
:toclevels: 4
:website: http://www.toppers.jp/

    バージョン: Release 1.7.1
    最終更新: 2015年5月30日

このドキュメントは，TOPPERS新世代カーネルに属する一連のリアルタイムカー
ネルの仕様を，統合的に記述したものである．今後，この仕様に対して，大き
い機能追加や仕様改変は行わず，これ以降は第3世代カーネル仕様として検討を
行う計画である．ただし，仕様が未完成の部分（特に動的生成対応カーネルに
関しては，仕様検討が不十分なところが多い）については，それを実装する時
点で追加で決定していくこととする．

なお，本文中から参照している図は，ファイルの最後にまとめて掲載してある．

----
  TOPPERS New Generation Kernel Specification

  Copyright (C) 2006-2015 by Embedded and Real-Time Systems Laboratory
              Graduate School of Information Science, Nagoya Univ., JAPAN
  Copyright (C) 2006-2015 by TOPPERS Project, Inc., JAPAN

 上記著作権者は，以下の (1)〜(3) の条件を満たす場合に限り，本ドキュメ
 ント（本ドキュメントを改変したものを含む．以下同じ）を使用・複製・改
 変・再配布（以下，利用と呼ぶ）することを無償で許諾する．
 (1) 本ドキュメントを利用する場合には，上記の著作権表示，この利用条件
     および下記の無保証規定が，そのままの形でドキュメント中に含まれて
     いること．
 (2) 本ドキュメントを改変する場合には，ドキュメントを改変した旨の記述
     を，改変後のドキュメント中に含めること．ただし，改変後のドキュメ
     ントが，TOPPERSプロジェクト指定の開発成果物である場合には，この限
     りではない．
 (3) 本ドキュメントの利用により直接的または間接的に生じるいかなる損害
     からも，上記著作権者およびTOPPERSプロジェクトを免責すること．また，
     本ドキュメントのユーザまたはエンドユーザからのいかなる理由に基づ
     く請求からも，上記著作権者およびTOPPERSプロジェクトを免責すること．

 本ドキュメントは，無保証で提供されているものである．上記著作権者およ
 びTOPPERSプロジェクトは，本ドキュメントに関して，特定の使用目的に対す
 る適合性も含めて，いかなる保証も行わない．また，本ドキュメントの利用
 により直接的または間接的に生じたいかなる損害に関しても，その責任を負
 わない．
----

== 仕様書で用いる記述項目と記号
この仕様書では，以下の記述項目を用いる．

【補足説明】::
 仕様本体の記述に対する補足事項を説明する．

【〜〜カーネルにおける規定】::
 TOPPERS新世代カーネルに属する特定のカーネルにおける追加仕様を規定する．

【〜〜仕様との関係】::
 この仕様と，μITRON4.0仕様またはμITRON4.0/PX仕様との違いについて説明する．

【未決定事項】::
 この仕様書の現時点のバージョンでは，決定されずに残っている事項について記述する．

【仕様決定の理由】::
 仕様を決定するにあたって考慮した事項について説明する．


「第４章 <<ch4_kernel_api>>」の章の各サービスコールおよび静的APIの仕様記述
においては，以下の記述項目を用いる．

【静的API】:: システムコンフィギュレーションファイル中で静的APIを記述する形式を規定する．
また，【C言語API】の項では，C言語からサービスコールを呼び出す形式を規定する．

【パラメータ】::
 サービスコールおよび静的APIに渡すパラメータの名称とデータ型を規定し，簡単な説明を行う．

【リターンパラメータ】::
 サービスコールが返すリターンパラメータの名称とデータ型を規定し，簡単な説明を行う．
【エラーコード】の項では，サービスコールおよび静的APIが返す可能性のあるメインエラーコードと，その検出条件を規定する．

【機能】::
 サービスコールおよび静的APIの機能を規定する．

TOPPERS新世代カーネルに属する特定のカーネルにおいてのみサポートするAPI
につしては，【サポートするカーネル】の項で，そのことを記述する．

また，「第４章 <<ch4_kernel_api>>」の章では，カーネルのAPIの種別とAPIをサ
ポートするカーネルの種類を表すために，次の記号を用いる．

〔T〕::
 タスクコンテキスト専用のサービスコールを示す．非タスクコンテキストから呼び出すと，E_CTXエラーとなる．

〔I〕::
 非タスクコンテキスト専用のサービスコールを示す．タスクコンテキストから呼び出すと，E_CTXエラーとなる．

〔TI〕::
タスクコンテキストからも非タスクコンテキストからも呼び出すことのできるサービスコールを示す．

〔S〕::
 静的APIを示す．

〔P〕::
 保護機能対応カーネルのみでサポートされているAPIを示す．保護機能対応でないカーネルでは，このAPIはサポートされない．

〔p〕::
 保護機能対応でないカーネルのみでサポートされているAPIを示す．保護機能対応カーネルでは，このAPIはサポートされない．

〔M〕::
 マルチプロセッサ対応カーネルのみでサポートされているAPIを示す．マルチプロセッサ対応でないカーネルでは，このAPIはサポートされない．

〔D〕::
動的生成対応カーネルのみでサポートされているAPIを示す．動的生成対応でないカーネルでは，このAPIはサポートされない．

また，エラーが発生する条件を表すために，次の記号を用いる．

〔s〕::
 サービスコールのみで発生するエラーを示す．静的APIでは，このエラーは発生しない．

〔S〕::
静的APIのみで発生するエラーを示す．サービスコールでは，このエラーは発生しない．

〔P〕::
保護機能対応カーネルのみで発生するエラーを示す．保護機能対応でないカーネルでは，このエラーは発生しない．

〔D〕::
 動的生成対応カーネルのみで発生するエラーを示す．動的生成対応でないカーネルでは，このエラーは発生しない．


== タグの付与方法
この仕様書では，トレーサビリティの確保のために，記述事項に対してタグを付与する．
具体的には，以下に該当する記述事項を，タグを付与する対象とする．

* 対象ソフトウェアの実装に対する要求事項や制限事項
* 対象ソフトウェアの仕様に対する一般要求事項
* 対象ソフトウェアの動作環境に対する要求事項
* ターゲット定義の規定

それに対して，用語の定義や補足説明，対象ソフトウェアを使用する上での推奨事項や注意事項，
仕様決定の理由，他の仕様との関係に対しては，タグを付与しない．

タグの形式と意味は次の通りである（xxxxは4桁の数字を表す）．
----
NGKIxxxx	TOPPERS新世代カーネル全体を対象とした記述
ASPSxxxx	TOPPERS/ASPカーネルを対象とした記述
FMPSxxxx	TOPPERS/FMPカーネルを対象とした記述
HRPSxxxx	TOPPERS/HRP2カーネルを対象とした記述
SSPSxxxx	TOPPERS/SSPカーネルを対象とした記述
ASSSxxxx	TOPPERS/ASP Safetyカーネルを対象とした記述
----
仕様書中では，ある記述事項に，*タグYYYYxxxx*
（YYYYは4文字の英文字，xxxxは4桁の数字を表す）が付与されていることを，
【YYYYxxxx】で表現する．それに対して，*タグYYYYxxxx* を参照する場合には，
［YYYYxxxx］と表記する．

